### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by Avishek-kr** [AmeyaJain-25/React-Social-Media-UI#1]
Hey ameya, I liked your React UI design, but social media icons(Google and Facebook) is not centered. 

![Screenshot_20210222_223630_com android chrome](https://user-images.githubusercontent.com/23341110/108743079-71b51300-755e-11eb-9324-0a48f7cee19b.jpg)

**Comment by AmeyaJain-25** [comment]
Thanks @Avishek-kr for letting me know the issue.
Will be making the changes required.
Thank you once again
